video: "MyVideo.mp4"
audio: "MyVideo.mp3"
srt: "MyVideo_corrected.srt"

segments:
  - name: "Hook"
    start: "00:00:00"
    end: "00:00:54"

  - name: "Reframing"
    start: "00:01:02"
    end: "00:01:52"
